/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.employeeframemaven;

import java.util.ArrayList;

/**
 *
 * @author Александр
 */
public class EditDialog extends javax.swing.JFrame {
    //String editedValue;
    String editedName;
    String editedSurname;
    String editedAge;
    String editedGender;
    String editedAddress;
    String editedSalary;

    /**
     * Creates new form EditDialog
     */
    public EditDialog(java.awt.Frame parent, boolean modal) {
    //    super(parent, modal);
        initComponents();
    }
    
    public String getEditedName() {
        return editedName;
    }
    public String getEditedSurname() {
        return editedSurname;
    }
    public String getEditedAge() {
        return editedAge;
    }
    public String getEditedGender() {
        return editedGender;
    }
    public String getEditedAddress() {
        return editedAddress;
    }
    public String getEditedSalary() {
        return editedSalary;
    }
    public void setVisible(boolean visible) {
        super.setVisible(visible);
    }
    
//    void setVisible(Object val, boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
    public void setVisible(Object Employee, boolean visible) {
        //this.editedValue = editedValue;
        this.jTextEditedFieldName.setText(this.editedName);
        this.jTextEditedFieldSurname.setText(this.editedSurname);
        this.jTextEditedFieldAge.setText(this.editedAge);
        this.jTextEditedFieldGender.setText(this.editedGender);
        this.jTextEditedFieldAddress.setText(this.editedAddress);
        this.jTextEditedFieldSalary.setText(this.editedSalary);
        super.setVisible(visible);
    }
    
//    public void setVisible(String editedValue, boolean visible) {
//        this.editedValue = editedValue;
//        this.txtFieldEditDialog.setText(editedValue);
//        super.setVisible(visible);
//    }
    
    public void setVisible(String editedName, String editedSurname, String editedAge, String editedGender, String editedAddress, String editedSalary, boolean visible) {
        this.editedName = editedName;
        this.editedSurname = editedSurname;
        this.editedAge = editedAge;
        this.editedGender = editedGender;
        this.editedAddress = editedAddress;
        this.editedSalary = editedSalary;
        this.jTextEditedFieldName.setText(editedName);
        this.jTextEditedFieldSurname.setText(editedSurname);
        this.jTextEditedFieldAge.setText(editedAge);
        this.jTextEditedFieldGender.setText(editedGender);
        this.jTextEditedFieldAddress.setText(editedAddress);
        this.jTextEditedFieldSalary.setText(editedSalary);
        super.setVisible(visible);
    }
    
    
    
    
//    
//    public void setVisibaleSurname(String editedValueSurname, boolean visible){
//        this.jTextEDitedFieldSurname.setText(this.editedValueSurname);
//        super.setVisible(visible);
//    }
//
//    public void setVisibaleAge(String editedValueAge, boolean visible){
//        this.jTextEditedFieldAge.setText(this.editedValueAge);
//        super.setVisible(visible);
//    }
//    
//    public void setVisibaleGender(String editedValueGender, boolean visible){
//        this.jTextEditedFieldGender.setText(this.editedValueGender);
//        super.setVisible(visible);
//    }
//    
//    public void setVisibaleAddress(String editedValueAddress, boolean visible){
//        this.jTextEditedFieldAddress.setText(this.editedValueAddress);
//        super.setVisible(visible);
//    }
//    
//    public void setVisibaleSalary(String editedValueSalary, boolean visible){
//        this.jTextEditedFieldSalary.setText(this.editedValueSalary);
//        super.setVisible(visible);
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextEditedFieldAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextEditedFieldAddress = new javax.swing.JTextField();
        jTextEditedFieldGender = new javax.swing.JTextField();
        jTextEditedFieldName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextEditedFieldSurname = new javax.swing.JTextField();
        jTextEditedFieldSalary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Age");

        jLabel5.setText("Address");

        jLabel4.setText("Gender");

        jTextEditedFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEditedFieldNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Salary");

        jLabel1.setText("Name");

        jLabel2.setText("Surname");

        JButtonAdd.setText("Edit");
        JButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextEditedFieldGender, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEditedFieldSurname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEditedFieldName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jTextEditedFieldAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEditedFieldSalary)
                    .addComponent(jTextEditedFieldAddress))
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(JButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditedFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEditedFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEditedFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEditedFieldNameActionPerformed

    private void JButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddActionPerformed
        //ArrayList<Employee> EmployeeArrayList = new ArrayList<>();
        
//        Object[] data = new Object[]{this.jTextFieldName.getText(), this.jTextFieldSurname.getText(),
//        Integer.parseInt(this.jTextFieldAge.getText()), Gender.valueOf(this.jTextFieldGender.getText()),
//        this.jTextFieldAddress.getText(), Double.parseDouble(this.jTextFieldSalary.getText())};
//        
//        //String value = this.jTextFieldName.getText();
//        if (!value.isEmpty()) {
//            this.editedValue = value;
//            this.setVisible(false);
//        }
//        Object [] value = new Object [] {
//                this.jTextEditedFieldName.getText(),
//                this.jTextEDitedFieldSurname.getText(),
//                this.jTextEditedFieldAge.getText(),
//                this.jTextEditedFieldGender.getText(),
//                this.jTextEditedFieldAddress.getText(),
//                this.jTextEditedFieldSalary.getText()
//        };
//        
//        Object[] editedValue = new Object[] {
//                this.getEditedValueName(),
//                this.getEditedValueSurname(),
//                this.getEditedValueAge(),
//                this.getEditedValueGender(),
//                this.getEditedValueAddress(),
//                this.getEditedValueSalary()
//        };
//            
//        //if(value.isEmpty())
//        for(int i = 0; i < value.length; i++){
//                if(value[i].equals(null)){
//                    value[i] = editedValue[i]; 
//                }
//                this.setVisible(false);
//            }
//            this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0), 
//                this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1),
//                this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 2), 
//                this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 3), 
//                this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 4), 
//                this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 5),
//            };       
        
        String value = this.jTextEditedFieldName.getText();
        if (!value.isEmpty()) {
            this.editedName = value;
            this.setVisible(false);
        }



        if(!this.jTextEditedFieldName.getText().isEmpty() 
            && !this.jTextEditedFieldSurname.getText().isEmpty()
            && !this.jTextEditedFieldAge.getText().isEmpty() 
            && !this.jTextEditedFieldGender.getText().isEmpty()
            && !this.jTextEditedFieldAddress.getText().isEmpty() 
            && !this.jTextEditedFieldSalary.getText().isEmpty())
        {
                this.editedName = this.jTextEditedFieldName.getText();
                this.editedSurname = this.jTextEditedFieldSurname.getText();
                this.editedAge = this.jTextEditedFieldAge.getText();
                this.editedGender = this.jTextEditedFieldGender.getText();
                this.editedAddress = this.jTextEditedFieldAddress.getText();
                this.editedSalary = this.jTextEditedFieldSalary.getText();
                this.setVisible(false);
            }
    }//GEN-LAST:event_JButtonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditDialog dialog = new EditDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextEditedFieldAddress;
    private javax.swing.JTextField jTextEditedFieldAge;
    private javax.swing.JTextField jTextEditedFieldGender;
    private javax.swing.JTextField jTextEditedFieldName;
    private javax.swing.JTextField jTextEditedFieldSalary;
    private javax.swing.JTextField jTextEditedFieldSurname;
    // End of variables declaration//GEN-END:variables

    
}
