/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.employeeframemaven;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//import org.json.SimpleJSON;


/**
 *
 * @author Александр
 */
public class EmployeeJFrameMaven extends javax.swing.JFrame {
    private final AddDialog addDialog;
    private final EditDialog editDialog;
    private final DefaultTableModel tableModel;
    private final PostgresDAO postgresDAO;

    /**
     * Creates new form EmployeeJFrame
     */
    public EmployeeJFrameMaven() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addDialog = new AddDialog(this, true);
        this.editDialog = new EditDialog(this, true);
        this.tableModel = (DefaultTableModel) this.jTable1.getModel();
        this.postgresDAO = new PostgresDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButtonAddEmployee = new javax.swing.JButton();
        jButtonEditEmployee = new javax.swing.JButton();
        jButtonExportEmployee = new javax.swing.JButton();
        jButtonDeleteEmployee = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonImportEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton8.setText("Import");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1010, 850));
        setType(java.awt.Window.Type.UTILITY);

        jButtonAddEmployee.setText("Add");
        jButtonAddEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEmployeeActionPerformed(evt);
            }
        });

        jButtonEditEmployee.setText("Edit");
        jButtonEditEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditEmployeeActionPerformed(evt);
            }
        });

        jButtonExportEmployee.setText("Export");
        jButtonExportEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportEmployeeActionPerformed(evt);
            }
        });

        jButtonDeleteEmployee.setText("Delete");
        jButtonDeleteEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDeleteEmployee.setMaximumSize(new java.awt.Dimension(46, 32));
        jButtonDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteEmployeeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setVerifyInputWhenFocusTarget(false);

        jButtonSearch.setActionCommand("Search");
        jButtonSearch.setLabel("Search");

        jButtonImportEmployee.setText("Import");
        jButtonImportEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImportEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportEmployeeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Age", "Gender", "Address", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(90, 64));
        jScrollPane1.setViewportView(jTable1);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(64, 35));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(65, 25));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(65, 25));
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonImportEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonExportEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonImportEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonAddEmployee.getAccessibleContext().setAccessibleName("JAdd");
        jButtonEditEmployee.getAccessibleContext().setAccessibleName("JEdit");
        jButtonExportEmployee.getAccessibleContext().setAccessibleName("JExport");
        jButtonDeleteEmployee.getAccessibleContext().setAccessibleName("JDelete");
        jButtonSearch.getAccessibleContext().setAccessibleName("JSearch");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEmployeeActionPerformed
        this.addDialog.setVisible(true);
        Object[] data = new Object[]{
            this.addDialog.getName(), 
            this.addDialog.getSurname(),
            this.addDialog.getAge(), 
            this.addDialog.getGender(), 
            this.addDialog.getAddress(),
            this.addDialog.getSalary()};
        //System.out.println(data[0]);
        //this.valueDao.add(this.AddDialog.getResult());
        this.tableModel.addRow(data);
    }//GEN-LAST:event_jButtonAddEmployeeActionPerformed
        
    
    private void jButtonEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditEmployeeActionPerformed
            if(this.jTable1.getSelectedRow() != -1){
            String value0 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 0));
            String value1 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 1));
            String value2 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 2));
            String value3 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 3));
            String value4 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 4));
            String value5 = String.valueOf(this.tableModel.getValueAt(this.jTable1.getSelectedRow(), 5));
            this.editDialog.setVisible(value0, value1, value2, value3, value4, value5, true);
        }
    }//GEN-LAST:event_jButtonEditEmployeeActionPerformed

    private void jButtonDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteEmployeeActionPerformed
        if(this.jTable1.getSelectedRow() != -1){
            int yesNo = JOptionPane.showConfirmDialog(null,"Are you sure you want to remove the row?", "Please confitm",  JOptionPane.YES_NO_OPTION);
            if(yesNo == JOptionPane.YES_OPTION){
                this.tableModel.removeRow(this.jTable1.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonDeleteEmployeeActionPerformed

    private void jButtonImportEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportEmployeeActionPerformed
       try{this.postgresDAO.getAll();
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButtonImportEmployeeActionPerformed

    private void jButtonExportEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportEmployeeActionPerformed
        //this.postgresDAO.update(this.addDialog(Employee(name, surname, age, gender, address, salary), true)); 
      
        //this.postgresDAO.update(this.addDialog(surname));
//              this.addDialog(getSurname();),
//              this.addDialog(getAge()),
//              this.addDialog(getGender()),
//              this.addDialog(getAddress()),
//              this.addDialog(getSalary())
//              );
    }//GEN-LAST:event_jButtonExportEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //SimpleJSON jsobObject;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrameMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrameMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrameMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeJFrameMaven.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeJFrameMaven().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonAddEmployee;
    private javax.swing.JButton jButtonDeleteEmployee;
    private javax.swing.JButton jButtonEditEmployee;
    private javax.swing.JButton jButtonExportEmployee;
    private javax.swing.JButton jButtonImportEmployee;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
